ResponseEntityを使ったpost処理の実装
Nagamoto-Koutarou/rasetech-java-6 pull request #2
Opened 2022-09-24 06:57 UTC by Nagamoto-Koutarou

postの処理にResponseEntityを使ったものを追加しました。

2022-09-27 03:02 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-09-27 03:02 UTC, YudaiNoda3576 commented on src/main/java/com/example/RestApiTraining/Controller.java
> +    @PostMapping("/post2")
URLには基本的に`post2` の`2` にあたるような数字はつけないことが多いです！
理由としては、
* 通常`2`のような数字はIDなどの識別子やバージョンの番号などに使われることが多いため
* URLはインターフェイスであるので誰が見ても意味が分かるように設計することが望ましいため
です。
なので、`post2`という命名ではなく、このURLにアクセスすることで何ができるのか？に着目して検討して見てください！


FYI
合わせて読んで見てください！

https://qiita.com/TakahiRoyte/items/949f4e88caecb02119aa

2022-09-27 03:02 UTC, YudaiNoda3576 commented on src/main/java/com/example/RestApiTraining/Controller.java
> +        int newId = Customer.size()+1;
ここの記述で想定通りの数字を取得できていますか？？

2022-09-27 03:02 UTC, YudaiNoda3576 commented on src/main/java/com/example/RestApiTraining/Controller.java
> +        URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
`http://localhost:8080`をハードコードせずに実装できるのでそのように修正のほどお願いします！

2022-09-27 03:02 UTC, YudaiNoda3576 commented on src/main/java/com/example/RestApiTraining/Controller.java
> +        return ResponseEntity.created(url).body("name successfully created");
レスポンスはJSON形式またはステータスコード201で返すように修正のほどお願いします！
こんな感じ↓

```
{
  "messages" : "name successfully created"
}
```

2022-09-27 03:02 UTC, YudaiNoda3576 commented on src/main/java/com/example/RestApiTraining/CreateForm.java
> +    public void setName(String name) {
setterメソッドは必要そうでしょうか？？

2022-09-28 16:37 UTC, Nagamoto-Koutarou commented on src/main/java/com/example/RestApiTraining/Controller.java
> +        int newId = Customer.size()+1;
![スクリーンショット (126)](https://user-images.githubusercontent.com/109859819/192836633-880899c6-1e6d-48d4-bf61-d27c960f4975.png)
![スクリーンショット (127)](https://user-images.githubusercontent.com/109859819/192836674-68b0f269-4f7c-4a00-80e9-66ccabb0798d.png)
上記画像のように、1∼5のidの次に6が表示されているので想定通りだと思っています。

2022-09-28 16:44 UTC, Nagamoto-Koutarou commented on src/main/java/com/example/RestApiTraining/Controller.java
> +    @PostMapping("/post2")
サイトありがとうございます！
今回はいずれもcustomerの情報を扱うので、getは/customers、postは/customers、patchとdeleteは/customers/{id}としました。getだけは複数のcustomer情報を扱うので複数形にしています。patchとdeleteも複数の中の1つと解釈すると複数形でもいいのかなと考えましたが、必要とするid情報は1つなので単数形にしました。

2022-09-28 16:46 UTC, Nagamoto-Koutarou commented on src/main/java/com/example/RestApiTraining/Controller.java
> +        return ResponseEntity.created(url).body("name successfully created");
Mapを使ってjsonで返すように修正しました。

2022-09-28 16:51 UTC, Nagamoto-Koutarou commented on src/main/java/com/example/RestApiTraining/CreateForm.java
> +    public void setName(String name) {
今回は不必要だったので削除しました。
今後はきちんと確認してからコミットプッシュするようにします。

2022-09-28 16:55 UTC, Nagamoto-Koutarou commented on src/main/java/com/example/RestApiTraining/Controller.java
> +        URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
Stringのtemplates変数の中にuriをいれて、そこからbuilderにいれるようにしたのですが、これであっているのでしょうか。

2022-09-29 03:00 UTC, YudaiNoda3576 reviewed
コメントしております！
ちなみにですが、nameのバリデーションについては別PRで対応する想定という認識であってますか？？

2022-09-29 03:00 UTC, YudaiNoda3576 commented on src/main/java/com/example/RestApiTraining/Controller.java
> +        String templates = "http://lacalhost:8080";
ここについてはまだハードコードされていますね！
（ハードコードが何かについても調べて頂き、それの何がいけないのかも共有ください！）
Javaコース受講生の大迫亜希さんのコードが参考になると思いますので覗いて見てください〜

FYI
https://github.com/akiosako/raisetech-subject10b

2022-09-29 03:00 UTC, YudaiNoda3576 commented on src/main/java/com/example/RestApiTraining/Controller.java
> +    @PatchMapping("/customer/{id}")
ご自身で考えられた観点は非常によく分かりますし、そのように考えられて使い分けられた点もとても素晴らしかったです！
が、Restにおけるエンドポイントは基本的に複数形にすることが望ましいとされています。
理由としては、WebAPI におけるエンドポイントはリソースを示しているからです。

詳しくはこのあたりの記事を参考にすると理解が深まるかもしれません！
https://qiita.com/mserizawa/items/b833e407d89abd21ee72
https://qiita.com/ryo88c/items/0a3c7861015861026e00

2022-09-29 03:00 UTC, YudaiNoda3576 commented on src/main/java/com/example/RestApiTraining/Controller.java
>                  .path("/post2/" + newId)
pathがpost2のままなので修正のほどよろしくお願いします。

2022-09-29 03:00 UTC, YudaiNoda3576 commented on src/main/java/com/example/RestApiTraining/Controller.java
> +        return new ResponseEntity<>("name successfully created", HttpStatus.OK);
Deleteの場合のみHTTPStatusを使用しているのは何か意図がありますか？？

2022-10-19 20:43 UTC, YudaiNoda3576 commented
![LGTM](https://image.lgtmoon.dev/184841)

2022-10-20 13:34 UTC, merged